project:
  start_year: 1990
  end_year: 2020

lake:
  charara_point: 
    - -16.53
    - 28.83
  coordinates:
    north: -15.75
    south: -17.25
    west: 27.25
    east: 29.00

era5:
  variables:
    - 10m_u_component_of_wind
    - 10m_v_component_of_wind
    - 2m_temperature
  region:
    - -10.0
    - 26.0
    - -18.0
    - 30.0
